# Generated by Django 4.1.4 on 2022-12-26 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ativoModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ativo', models.CharField(max_length=25, verbose_name='Nome do Ativo: ')),
                ('Resp', models.CharField(max_length=100, verbose_name='Responsável: ')),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
            },
        ),
        migrations.CreateModel(
            name='itemModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=50, verbose_name='Ítem: ')),
                ('Quant', models.IntegerField(verbose_name='Quantidade: ')),
            ],
            options={
                'verbose_name': 'Ítem',
                'verbose_name_plural': 'Ítens',
            },
        ),
        migrations.CreateModel(
            name='saidaModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('quant', models.IntegerField(verbose_name='Quantidade')),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ativomodels', verbose_name='Ativo')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.itemmodels', verbose_name='Ítem')),
            ],
            options={
                'verbose_name': 'Saida',
                'verbose_name_plural': 'Saídas',
            },
        ),
    ]
