# Generated by Django 4.1.4 on 2022-12-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodels',
            name='Quant',
            field=models.PositiveIntegerField(verbose_name='Quantidade: '),
        ),
        migrations.AlterField(
            model_name='saidamodels',
            name='quant',
            field=models.PositiveIntegerField(verbose_name='Quantidade'),
        ),
    ]
