# Generated by Django 4.1.4 on 2023-01-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_itemmodels_quant_alter_saidamodels_quant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saidamodels',
            name='data',
            field=models.DateField(max_length=10, verbose_name='Data'),
        ),
    ]
